baseURL = "https://master.d2asm3jdpavcgj.amplifyapp.com/"
languageCode = "en-us"
title = "South Chertanovo Records"
theme = "detox"

[Params]
    author = "South Chertanovo Records"
    description = "We're Working on It"