baseURL = "https://www.chertanovo.link/"
languageCode = "en-us"
title = "South Chertanovo Records"
theme = "detox"

[Params]
    author = "South Chertanovo Records"
    description = "Listen our music on your favourite streaming platform"