baseURL = "https://www.chertanovo.link/"
languageCode = "en-us"
title = "South Chertanovo Records"
theme = "detox"
enableRobotsTXT = true
googleAnalytics = "UA-166218478-1"

[Params]
    author = "South Chertanovo Records"
    description = "Listen our music on your favourite streaming platform"